sudo: false
language: python

python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres

env:
  global:
  - PGUSER=postgres
  - PG_PASSWORD=

install:
  - pip install poetry
  - poetry develop

script:
  - poetry run py.test --cov
